apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - release.yaml
  - repository-seafile.yaml
  - repository-bitnami.yaml
  - storage.yaml
  - mariadb-secret.yaml
  - mariadb-storage.yaml
