apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository-seafile.yaml
  - mariadb-service.yaml
  - mariadb-deployment.yaml
  - mariadb-init-configmap.yaml
  - release-seafile.yaml
  - storage.yaml
  - mariadb-secret.yaml
  - mariadb-storage.yaml
  - seahub-settings-configmap.yaml
