apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-seafile
  namespace: seafile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-seafile
  template:
    metadata:
      labels:
        app: mariadb-seafile
    spec:
      containers:
        - name: mariadb
          image: mariadb:12
          imagePullPolicy: IfNotPresent
          ports:
            - name: mysql
              containerPort: 3306
          envFrom:
            - secretRef:
                name: mariadb-seafile-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mariadb-seafile-data
