apiVersion: v1
kind: Service
metadata:
  name: openerp-postgres
  namespace: openerp
spec:
  ports:
    - port: 5432
  selector:
    app: openerp-postgres
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: openerp-backend
  namespace: openerp
spec:
  ports:
    - port: 8080
  selector:
    app: openerp-backend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: openerp-frontend
  namespace: openerp
spec:
  ports:
    - port: 3000
  selector:
    app: openerp-frontend
  type: ClusterIP
