apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n
data:
  N8N_PORT: "5678"
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
  N8N_SECURE_COOKIE: "false"
  N8N_PROTOCOL: "http"
  GENERIC_TIMEZONE: "Europe/Amsterdam"
  TZ: "Europe/Amsterdam"
  NODES_EXCLUDE: "[]"  
  N8N_HOST: "n8n.hansjlachmann.net"                                                                              
  WEBHOOK_URL: "https://n8n.hansjlachmann.net"                                                                   
                                                
