apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openerp
  namespace: openerp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - openerp.hansjlachmann.net
      secretName: openerp-tls
  rules:
    - host: openerp.hansjlachmann.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openerp-frontend
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: openerp-backend
                port:
                  number: 8080
