apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openerp
resources:
  - ../../base/openerp/
  - ingress.yaml
  # - openerp-secret.yaml  # Uncomment after encrypting with SOPS
