apiVersion: v1
kind: ConfigMap
metadata:
  name: audiobookshelf-config
  namespace: audiobookshelf
data:
  environment:
    METADATA_PATH=/var/lib/audiobookshelf/metadata
    CONFIG_PATH=/var/lib/audiobookshelf/config
    PORT=3005
    HOST=127.0.0.1

