apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: 21d3e1bf-81c0-4405-a31c-3593bb2a01ef
    credentials-file: /etc/cloudflared/credentials.json

    loglevel: info

    ingress:
      - hostname: linkding.hansjlachmann.net
        service: http://linkding.linkding.svc.cluster.local:9090

      - hostname: mealie.hansjlachmann.net
        service: http://mealie.mealie.svc.cluster.local:9000

      - hostname: grafana.hansjlachmann.net
        service: http://grafana.monitoring.svc.cluster.local:80

      # Default behavior
      - service: http_status:404
